config/routes.rb
Rails.application.routes.draw do
  root 'site/welcome#index'
  get  'backoffice', to: 'admins_backoffice/welcome#index' # Dashboard

  namespace :site do
    root 'welcome#index'
    get  'search',                   to: 'search#questions'
    get  'subject/:id/:description', to: 'search#subject', as: 'search_subject'
    get  'subjects',                 to: 'subjects#index'
    get  'subjects/:id',             to: 'subjects#show', as: 'subject'
    get  'questions',                to: 'questions#index'
    post 'answer',                   to: 'answer#question'
  end

  namespace :users_backoffice do
    root   'welcome#index'
    get    'welcome/index'
    get    'profile',                to: 'profile#edit'
    patch  'profile',                to: 'profile#update'
    get    'zip_code',               to: 'zip_code#show'
    get    'favorites',              to: 'favorite_questions#index'
    delete 'favorite_questions/:id', to: 'favorite_questions#destroy', as: 'favorite_question'
    post   'favorite',               to: 'favorite_questions#favorite'
  end

  namespace :admins_backoffice do
    root 'welcome#index'
    get  'dashboard', to: 'welcome#index' # Dashboard

    resources :admins,   except: [:show]
    resources :subjects, except: [:show]
    resources :questions
  end

  devise_for :users
  devise_for :admins, skip: [:registrations]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/site/answer_controller.rb
class Site::AnswerController < SiteController
  def question
    answer = Rails.cache.read(params[:answer]).split("@@")

    @question_id = answer.first
    @correct = ActiveModel::Type::Boolean.new.cast(answer.last)

    if user_signed_in?
      UserStatistic.set_statistic_by_answer(current_user, @correct)
    end
  end
end

app/controllers/site/questions_controller.rb
class Site::QuestionsController < SiteController
  def index
    @questions = Question.by_filter(params[:field] ||= 'created_at', params[:order] ||= 'DESC', params[:page])
  end
end

app/controllers/site/search_controller.rb
class Site::SearchController < SiteController
  def questions
    @questions = Question.search(params[:term], page: params[:page], per_page: 10)
  end

  def subject
    @questions = Question.find_by_subject(params[:id]).page(params[:page])
  end
end

app/controllers/site/subjects_controller.rb
class Site::SubjectsController < SiteController
  def index
    @subjects = Subject.all.page(params[:page]).per(30)
  end

  def show
    @subject = Subject.find(params[:id])
    @questions = Subject.find_all_questions_paged_by_subject_id(params[:id], params[:page])
  end
end

app/controllers/site/welcome_controller.rb
class Site::WelcomeController < SiteController
  def index
    @questions = Question.latest
    @subjects = Subject.more_popular
  end
end

app/controllers/site_controller.rb
class SiteController < ApplicationController
  layout 'site'
end

app/helpers/site/answer_helper.rb
module Site::AnswerHelper
end

app/helpers/site/questions_helper.rb
module Site::QuestionsHelper
end

app/helpers/site/search_helper.rb
module Site::SearchHelper
end

app/helpers/site/subjects_helper.rb
module Site::SubjectsHelper
end

app/helpers/site/welcome_helper.rb
module Site::WelcomeHelper
end

app/helpers/site_helper.rb
module SiteHelper
end

app/views/site/shared/_questions.html.erb
<% unless @questions.blank? %>
  <% @questions.each do |question| %>
    <div id="question_<%= question.id %>" class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title">
          <%= sanitize question.description %>
        </h3>

        <% if user_signed_in? %>
          <div>
            <%= form_with url: users_backoffice_favorite_path, class: "navbar-form" do |f| %>
              <%= f.hidden_field :question_id, class: "form-control", value: question.id %>
              <%= f.submit 'Favoritar', class: "btn btn-default" %>
            <% end %>
          </div>
        <% end %>
      </div>

      <%= form_with url: site_answer_path do |form|%>
        <div class="list-group">
          <ul>
            <% question.answers.each do |answer| %>
              <li class="radio">
                <label>
                  <%= radio_button_tag 'answer', answer.id %>
                  <%= answer.description %>
                </label>
              </li>
            <% end %>
          </ul>
        </div>

        <div class="panel-footer" style="display: flex; justify-content: space-between; align-items: center;">
          <%= link_to site_search_subject_path(question.subject_id, question.subject.description), style: "color: white; margin-right: 10px; text-decoration: none;" do %>
            <span class="label label-info">
              <%= "#{question.subject.description} (#{question.subject.questions_count})" %>
            </span>
          <% end %>

          <div>
            <b><small id="message_<%= question.id %>"></small></b>
            <%= form.submit 'Responder', class: "btn btn-default" %>
          </div>
        </div>
      <% end %>
    </div>
  <% end %>
<% else %>
  <p class="lead">
    <small>
      Nenhuma pergunta foi encontrada para o termo: <b><%= params[:term] %></b>
    </small>
  </p>
<% end %>