config/routes.rb
Rails.application.routes.draw do
  root 'site/welcome#index'
  get  'backoffice', to: 'admins_backoffice/welcome#index' # Dashboard

  namespace :site do
    root 'welcome#index'
    get  'search',                   to: 'search#questions'
    get  'subject/:id/:description', to: 'search#subject', as: 'search_subject'
    get  'subjects',                 to: 'subjects#index'
    get  'subjects/:id',             to: 'subjects#show', as: 'subject'
    get  'questions',                to: 'questions#index'
    post 'answer',                   to: 'answer#question'
  end

  namespace :users_backoffice do
    root   'welcome#index'
    get    'welcome/index'
    get    'profile',                to: 'profile#edit'
    patch  'profile',                to: 'profile#update'
    get    'zip_code',               to: 'zip_code#show'
    get    'favorites',              to: 'favorite_questions#index'
    delete 'favorite_questions/:id', to: 'favorite_questions#destroy', as: 'favorite_question'
    post   'favorite',               to: 'favorite_questions#favorite'
  end

  namespace :admins_backoffice do
    root 'welcome#index'
    get  'dashboard', to: 'welcome#index' # Dashboard

    resources :admins,   except: [:show]
    resources :subjects, except: [:show]
    resources :questions
  end

  devise_for :users
  devise_for :admins, skip: [:registrations]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/subject.rb
class Subject < ApplicationRecord
  has_many :questions
  paginates_per 10

  validates :description, presence: true
  validates :description, length: { minimum: 2, allow_blank: true }

  after_destroy  :decreases_total_number_of_questions

  scope :more_popular, -> { order(questions_count: :desc).limit(6) }

  scope :find_all_questions_paged_by_subject_id, -> (id, page) {
    find(id).questions.includes(:answers).page(page).per(10)
  }

  private
    def decreases_total_number_of_questions
      AdminStatistic.decreases_total_number_by_event(AdminStatistic::EVENTS[:total_questions], self.questions_count)
    end
end

app/controllers/admins_backoffice/admins_controller.rb
class AdminsBackoffice::AdminsController < AdminsBackofficeController
  before_action :verify_password, only: [:update]
  before_action :set_admin, only: %i[edit update destroy]

  def index
    @admins = Admin.all.page(params[:page])
  end

  def edit; end

  def update
    if @admin.update(params_admin)
      AdminMailer.update_email(current_admin, @admin).deliver_now
      redirect_to admins_backoffice_admins_path, notice: 'Administrador atualizado com sucesso!'
    else
      render :edit
    end
  end

  def new
    @admin = Admin.new
  end

  def create
    @admin = Admin.new(params_admin)

    if @admin.save
      redirect_to admins_backoffice_admins_path, notice: 'Administrador criado com sucesso!'
    else
      render :new
    end
  end

  def destroy
    if @admin.destroy
      redirect_to admins_backoffice_admins_path, notice: 'Administrador excluído com sucesso!'
    else
      redirect_to admins_backoffice_admins_path
    end
  end

  private

  def verify_password
    if params[:admin][:password].blank? && params[:admin][:password_confirmation].blank?
      params[:admin].extract!(:password, :password_confirmation)
    end
  end

  def set_admin
    @admin = Admin.find(params[:id])
  end

  def params_admin
    params.require(:admin).permit(:email, :password, :password_confirmation)
  end
end

app/controllers/admins_backoffice/questions_controller.rb
class AdminsBackoffice::QuestionsController < AdminsBackofficeController
  before_action :set_question, only: [:edit, :update, :destroy]
  before_action :get_subjects, only: [:edit, :update, :new, :create]

  def index
    @questions = Question.includes(:subject).order(:description).page(params[:page])
  end

  def edit
  end

  def update
    if @question.update(params_question)
      redirect_to admins_backoffice_questions_path, notice: 'Questão atualizada com sucesso!'
    else
      render :edit
    end
  end

  def new
    @question = Question.new
  end

  def create
    @question = Question.new(params_question)

    if @question.save
      redirect_to admins_backoffice_questions_path, notice: 'Questão criada com sucesso!'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    if @question.destroy
      redirect_to admins_backoffice_questions_path, notice: 'Questão excluída com sucesso!'
    else
      redirect_to admins_backoffice_questions_path
    end
  end

  private
    def set_question
      @question = Question.find(params[:id])
    end
    
    def params_question
      params.require(:question).permit(
        :description,
        :subject_id,
        answers_attributes: [
          :id,
          :description,
          :correct,
          :_destroy
        ]
      )
    end

    def get_subjects
      @subjects = Subject.all
    end
    
end

app/controllers/admins_backoffice/subjects_controller.rb
class AdminsBackoffice::SubjectsController < AdminsBackofficeController
  before_action :set_subject, only: [:edit, :update, :destroy]

  def index
    respond_to do |format|
      format.html { @subjects = Subject.all.page(params[:page]) }
      format.pdf  { @subjects = Subject.all }
      format.json { @subjects = Subject.all }
    end
  end
  
  def edit
  end
  
  def update
    if @subject.update(params_subject)
      redirect_to admins_backoffice_subjects_path, notice: 'Assunto atualizado com sucesso!'
    else
      render :edit
    end
  end
  
  def new
    @subject = Subject.new
  end
  
  def create
    @subject = Subject.new(params_subject)

    if @subject.save
      redirect_to admins_backoffice_subjects_path, notice: 'Assunto criado com sucesso!'
    else
      render :new
    end
  end
  
  def destroy
    if @subject.destroy
      redirect_to admins_backoffice_subjects_path, notice: 'Assunto excluído com sucesso!'
    else
      redirect_to admins_backoffice_subjects_path
    end
  end
  
  
  private
    def set_subject
      @subject = Subject.find(params[:id])
    end
    
    def params_subject
      params.require(:subject).permit(:description)
    end
end

app/controllers/admins_backoffice/welcome_controller.rb
class AdminsBackoffice::WelcomeController < AdminsBackofficeController
  def index
    @total_users = AdminStatistic.total_users
    @total_questions = AdminStatistic.total_questions
  end
end

app/controllers/admins_backoffice_controller.rb
class AdminsBackofficeController < ApplicationController
  before_action :authenticate_admin!
  layout 'admins_backoffice'
end

app/controllers/site/subjects_controller.rb
class Site::SubjectsController < SiteController
  def index
    @subjects = Subject.all.page(params[:page]).per(30)
  end

  def show
    @subject = Subject.find(params[:id])
    @questions = Subject.find_all_questions_paged_by_subject_id(params[:id], params[:page])
  end
end

app/helpers/admins_backoffice/admins_helper.rb
module AdminsBackoffice::AdminsHelper
end

app/helpers/admins_backoffice/questions_helper.rb
module AdminsBackoffice::QuestionsHelper
end

app/helpers/admins_backoffice/subjects_helper.rb
module AdminsBackoffice::SubjectsHelper
end

app/helpers/admins_backoffice/welcome_helper.rb
module AdminsBackoffice::WelcomeHelper
end

app/helpers/admins_backoffice_helper.rb
module AdminsBackofficeHelper
  def translate_attribute(model, method)
    model.human_attribute_name(method)
  end
end

app/helpers/site/subjects_helper.rb
module Site::SubjectsHelper
end

app/views/admins_backoffice/subjects/edit.html.erb
<%= render partial: 'admins_backoffice/subjects/shared/form', locals: { action_message: t('messages.editing', model: @subject.model_name.human) } %>

app/views/admins_backoffice/subjects/index.html.erb
<%# Page title %>
<div class="row">
  <div class="col-lg-12">
    <h1 class="page-header">
      <%= t('messages.listing', model: @subjects.model_name.human(count: 2)) %>
    </h1>
  </div> <!-- /.col-lg-12 -->
</div> <!-- /.row -->

<div class="row" style="margin-bottom: 15px;">
  <div class="col-lg-12">
    <%= link_to new_admins_backoffice_subject_path, class: "btn btn-success" do %>
      <i class="fa fa-plus"></i> Novo assunto
    <% end %>

    <%= link_to admins_backoffice_subjects_path(format: :pdf), target: :_blank, class: 'btn btn-default' do %>
      <i class="fa fa-file-pdf-o"></i> <%= t('buttons.pdf') %>
    <% end %>
  </div>
</div>

<%# Table %>
<div class="row">
  <div class="col-lg-12">
    <div class="table-responsive">
      <table class="table table-striped table-bordered table-hover">
        <thead>
          <tr>
            <th><%= translate_attribute(@subjects, :id) %></th>
            <th><%= translate_attribute(@subjects, :description) %></th>
            <th>Ações</th>
          </tr>
        </thead>
        <tbody>
          <% @subjects.each do |subject| %>
            <tr>
              <td><%= subject.id %></td>
              <td><%= subject.description %></td>
              <th>
                <%= link_to edit_admins_backoffice_subject_path(subject), class: "btn btn-primary btn-circle", title: t('buttons.edit') do %>
                  <i class="fa fa-edit"></i>
                <% end %>
                <%= link_to admins_backoffice_subject_path(subject), method: :delete, data: { confirm: t('messages.confirm_with') }, class: "btn btn-danger btn-circle", title: t('buttons.destroy') do %>
                  <i class="fa fa-trash-o"></i>
                <% end %>
              </th>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div> <!-- /.table-responsive -->
  </div> <!-- /.col-lg-12 -->
</div> <!-- /.row -->

<%# Pagination %>
<div class="row">
  <div class="col-lg-12 text-center">
    <%= paginate @subjects %>
  </div> <!-- /.col-lg-12 -->
</div> <!-- /.row -->

app/views/admins_backoffice/subjects/new.html.erb
<%= render partial: 'admins_backoffice/subjects/shared/form', locals: { action_message: t('messages.new', model: @subject.model_name.human) } %>