config/routes.rb
Rails.application.routes.draw do
  root 'site/welcome#index'
  get  'backoffice', to: 'admins_backoffice/welcome#index' # Dashboard

  namespace :site do
    root 'welcome#index'
    get  'search',                   to: 'search#questions'
    get  'subject/:id/:description', to: 'search#subject', as: 'search_subject'
    get  'subjects',                 to: 'subjects#index'
    get  'subjects/:id',             to: 'subjects#show', as: 'subject'
    get  'questions',                to: 'questions#index'
    post 'answer',                   to: 'answer#question'
  end

  namespace :users_backoffice do
    root   'welcome#index'
    get    'welcome/index'
    get    'profile',                to: 'profile#edit'
    patch  'profile',                to: 'profile#update'
    get    'zip_code',               to: 'zip_code#show'
    get    'favorites',              to: 'favorite_questions#index'
    delete 'favorite_questions/:id', to: 'favorite_questions#destroy', as: 'favorite_question'
    post   'favorite',               to: 'favorite_questions#favorite'
  end

  namespace :admins_backoffice do
    root 'welcome#index'
    get  'dashboard', to: 'welcome#index' # Dashboard

    resources :admins,   except: [:show]
    resources :subjects, except: [:show]
    resources :questions
  end

  devise_for :users
  devise_for :admins, skip: [:registrations]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/admins_backoffice/welcome_controller.rb
class AdminsBackoffice::WelcomeController < AdminsBackofficeController
  def index
    @total_users = AdminStatistic.total_users
    @total_questions = AdminStatistic.total_questions
  end
end

app/controllers/site/answer_controller.rb
class Site::AnswerController < SiteController
  def question
    answer = Rails.cache.read(params[:answer]).split("@@")

    @question_id = answer.first
    @correct = ActiveModel::Type::Boolean.new.cast(answer.last)

    if user_signed_in?
      UserStatistic.set_statistic_by_answer(current_user, @correct)
    end
  end
end

app/controllers/site/questions_controller.rb
class Site::QuestionsController < SiteController
  def index
    @questions = Question.by_filter(params[:field] ||= 'created_at', params[:order] ||= 'DESC', params[:page])
  end
end

app/controllers/site/search_controller.rb
class Site::SearchController < SiteController
  def questions
    @questions = Question.search(params[:term], page: params[:page], per_page: 10)
  end

  def subject
    @questions = Question.find_by_subject(params[:id]).page(params[:page])
  end
end

app/controllers/site/subjects_controller.rb
class Site::SubjectsController < SiteController
  def index
    @subjects = Subject.all.page(params[:page]).per(30)
  end

  def show
    @subject = Subject.find(params[:id])
    @questions = Subject.find_all_questions_paged_by_subject_id(params[:id], params[:page])
  end
end

app/controllers/site/welcome_controller.rb
class Site::WelcomeController < SiteController
  def index
    @questions = Question.latest
    @subjects = Subject.more_popular
  end
end

app/controllers/site_controller.rb
class SiteController < ApplicationController
  layout 'site'
end

app/controllers/users_backoffice/welcome_controller.rb
class UsersBackoffice::WelcomeController < UsersBackofficeController
  def index
    @user_statistic = UserStatistic.find_or_create_by(user: current_user)
  end
end

app/helpers/admins_backoffice/welcome_helper.rb
module AdminsBackoffice::WelcomeHelper
end

app/helpers/site/answer_helper.rb
module Site::AnswerHelper
end

app/helpers/site/questions_helper.rb
module Site::QuestionsHelper
end

app/helpers/site/search_helper.rb
module Site::SearchHelper
end

app/helpers/site/subjects_helper.rb
module Site::SubjectsHelper
end

app/helpers/site/welcome_helper.rb
module Site::WelcomeHelper
end

app/helpers/site_helper.rb
module SiteHelper
end

app/helpers/users_backoffice/welcome_helper.rb
module UsersBackoffice::WelcomeHelper
end

app/views/site/welcome/index.html.erb
<!-- Main component for a primary marketing message or call to action -->
<div class="jumbotron">
  <h2>Bem-vindo ao Time to Answer!</h2>
  <p>Um site de perguntas e respostas para praticar os seus estudos. Cadastre-se para ter acesso a todas as perguntas e favoritá-las!</p>
</div>

<div class="page-header">
  <h3>Assuntos mais populares</h3>
</div>
<div class="row">
  <% @subjects.each do |subject| %>
    <div class="col-sm-6 col-md-4" >
      <%= link_to site_subject_path(subject.id) do %>
        <div class="thumbnail">
          <div class="caption">
            <h4><%= subject.description.truncate(30) %></h4>
            <p><%= "#{ subject.questions_count } #{ subject.questions_count != 1 ? "perguntas" : "pergunta" }" %></p>
          </div>
        </div>
      <% end %>
    </div>
  <% end %>
</div>
<div class="text-right">
  <%= link_to 'Ver todos...', site_subjects_path %>
</div>

<div class="page-header">
  <h3>Perguntas mais recentes</h3>
</div>
<%= render partial: 'site/shared/questions' %>
<div class="text-right">
  <%= link_to 'Ver todas...', site_questions_path %>
</div>